### PR TITLE
Corrected visual lags and crash bug

### LINKED ISSUE #88: [BUG] Crash when clicking the followers button w/o connection + Slow side menu buttons (low priority)
I experienced a crash when clicking on the followers button of the side menu of the application.

It gave me the following error:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.github.sdp_begreen.begreen, PID: 26583
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
     Caused by: com.github.sdp_begreen.begreen.exceptions.DatabaseTimeoutException: Timeout, cant connect with database
        at com.github.sdp_begreen.begreen.firebase.FirebaseDB.getNode(FirebaseDB.kt:281)
        at com.github.sdp_begreen.begreen.firebase.FirebaseDB.access$getNode(FirebaseDB.kt:29)
        at com.github.sdp_begreen.begreen.firebase.FirebaseDB$getNode$1.invokeSuspend(Unknown Source:21)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
        at com.github.sdp_begreen.begreen.activities.MainActivity.handleDrawerMenuItemClick(MainActivity.kt:234)
        at com.github.sdp_begreen.begreen.activities.MainActivity.onCreate$lambda$2(MainActivity.kt:92)
        at com.github.sdp_begreen.begreen.activities.MainActivity.$r8$lambda$_ivrTSngI8kFmJYGp45P3xXAKow(Unknown Source:0)
        at com.github.sdp_begreen.begreen.activities.MainActivity$$ExternalSyntheticLambda5.onNavigationItemSelected(Unknown Source:4)
        at com.google.android.material.navigation.NavigationView$1.onMenuItemSelected(NavigationView.java:303)
        at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:836)
        at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:159)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:987)
        at com.google.android.material.internal.NavigationMenuPresenter$1.onClick(NavigationMenuPresenter.java:494)
        at android.view.View.performClick(View.java:7448)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

I do not really expect an application crash when I have no connection, how will I keep the streets clean? 😢

Also, clicking on these side menu buttons slow down the app considerably (there is a small lag before the corresponding fragment opens).

### PR DESCRIPTION
**Pull request by LucaCarroz**
This PR fixes the following:
- The transitions to side bar menus are now smooth 
- When clickin the "post" button, we get instantly redirected to the camera fragment, while the posting is in process, to avoid blocking the user on that fragment.

### CODE REVIEW

**Review by david-schroeter — APPROVED** [review]
Good job Luca in fixing those Bugs.And in improving the user experience in launching the sendPost in background to not block the UI for too long when performing check before posting it.

It looks all good to me.

File: app/src/main/java/com/github/sdp_begreen/begreen/activities/MainActivity.kt [hunk 1]
```diff
@@ -34,10 +45,110 @@ import java.util.*
...
+
+    private suspend fun processContest(
+        contest: Contest,
+        userId: String,
+        participationMap: Map<String, Boolean>,
+        trashCategory: TrashCategory,
+        location: CustomLatLng
+    ) {
+        location.toMapLocation()?.let {
+            if (participationMap[contest.id] == true &&
```
Comment (AlSchlo) [inline app/src/main/java/com/github/sdp_begreen/begreen/activities/MainActivity.kt:129]: Why `==` true?

Comment (LucaCarroz) [reply app/src/main/java/com/github/sdp_begreen/begreen/activities/MainActivity.kt:129]: Because `participationMap[contest.id]` can be null. That way, if it is indeed null, `null == true` will return false and we wont satisfy the `if` condition
